# This should be the content of your docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend/model_cache:/app/src/backend/model_cache