version: '3.8' # It's good practice to add a version

services:
  app:
    build: . # This tells Docker to find and use Dockerfile
    ports:
      - "8000:8000"
    # No volumes, no command override. 
    # The image is self-contained and uses the CMD from the Dockerfile.