name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Make render-build.sh executable
      run: |
        chmod +x render-build.sh
        git update-index --chmod=+x render-build.sh
    
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.3
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }} # Service ID from Render
        api_key: ${{ secrets.RENDER_API_KEY }} # API Key from Render
        clear_cache: true # Clear build cache
        wait: true # Wait for deployment to complete
        
    - name: Deployment Status
      run: |
        echo "Deployment to Render has been triggered"
        echo "Check the deployment status in your Render dashboard" 